# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OA6AWCXRW2HIALnhgt1GErM3Q8CS1qMT
"""

!wget https://clck.ru/YT75w
!pip install yandex_geocoder
!unzip YT75w

import pandas as pd

df1 = pd.read_excel("обращения граждан на портале народный контроль.xlsx")
df2 = pd.read_excel("Просьбы жителей по благоустройству.xlsx")

df2

df1

df2['adress'] = 'Чебоксары ' + df2['Адрес обращения'] + ' ' + df2['Дом']
df2

from decimal import Decimal

from yandex_geocoder import Client


client = Client("9e4ea4e8-8227-4f2b-9d58-35e65d727701")

coordinates = client.coordinates("Чебоксары улица Кукшумская 9")

coordinates

addresses = []
for i in range(len(df2)):
  if not df2['adress'].iloc[i] in addresses:
    addresses.append(df2['adress'].iloc[i])
print(len(addresses))

coords = []
for i in addresses:
  try:
    coords.append(client.coordinates(i))
  except:
    coords.append((0,0))

m = [addresses, coords]

m[1].index((0,0))

m[0][1899]

m[1][500] = client.coordinates('Чебоксары проезд Мясокомбинатский 9')
m[1][1315] = client.coordinates('п. Сосновка, ул. Нагорная 7')
m[1][1564] = client.coordinates('Чебоксары проезд Мясокомбинатский 55 корп. Б')
m[1][1593] = client.coordinates('Чебоксары проезд Мясокомбинатский 9Д')
m[1][1635] = client.coordinates('Чебоксары проезд Мясокомбинатский 93 корп. К')

m[1][1899] = client.coordinates('Чебоксары проезд Мясокомбинатский 17А')

m[1]

for i in range(len(df2)):
   a = m[1][m[0].index(df2['adress'].iloc[i])]
   df2.loc[i, 'coord1'] = float(a[0])
   df2.loc[i, 'coord2'] = float(a[1])
df2

df2.to_csv('df2_w_coords.csv')

with open('addrcoord3.pickle', 'wb') as f:
  pickle.dump(m, f)

m2 = []
for i in range(len(df2)):
  m2.append((df2['текст обращения'].iloc[i], df2['coord2'].iloc[i], df2['coord1'].iloc[i]))

with open('points.pickle', 'wb') as f:
  pickle.dump(m2, f)

import pandas as pd

df21 = pd.read_csv('/content/df2_w_coords.csv')
df22 = pd.read_csv('/content/просьбы_жителей_add_type.csv')

df21

df22

circles_w_name = []
for i in range(len(df22)):
  circles_w_name.append((df22['street'].iloc[i], df21['coord2'].iloc[i], df21['coord1'].iloc[i]))

circles_w_name

import pickle
with open('points2.pickle', 'wb') as f:
  pickle.dump(circles_w_name, f)

import pandas as pd

soc = pd.read_csv('/content/соц_объекты.csv')
soc

soc_places = []
for i in range(len(soc)):
  soc_places.append((soc['type'].iloc[i], soc['Широта'].iloc[i], soc['Долгота'].iloc[i]))
soc_places

import pickle
with open('soc_places.pickle', 'wb') as f:
  pickle.dump(soc_places, f)